<template>
	<div>
		<top-title :title='"客服统计"' />
		<ser-body :workload='workload' :Quality='Quality' :Performance='Performance'/>
	</div>
</template>

<script>
	const topTitle = () => import('@/components/topTitle');
	const serBody = () => import('@/components/Statistical/stService/serBody');
	export default {
		components: {
			topTitle,
			serBody
		},
		data() {
			return {
				workload: [{
					date: '2016-05-02',
					name: '符号',
					session: '3',
					notReturn: '33%',
					amount: '0',
					invalids: '2',
					message: '3',
					loginTime: '26小时36分',
					onlineTime: '16小时36分',
					loginAccounted: '43%',
					outTime: '6小时36分',
					outAccounted: '22%',
					restTime: '6小时36分',
					resAccounted: '22%'
				}, {
					date: '2016-05-02',
					name: '符号',
					session: '2',
					notReturn: '33%',
					amount: '0',
					invalids: '2',
					message: '3',
					loginTime: '26小时36分',
					onlineTime: '16小时36分',
					loginAccounted: '43%',
					outTime: '6小时36分',
					outAccounted: '22%',
					restTime: '6小时36分',
					resAccounted: '22%'
				}, {
					date: '2016-05-02',
					name: '符号',
					session: '2',
					notReturn: '33%',
					amount: '0',
					invalids: '2',
					message: '3',
					loginTime: '26小时36分',
					onlineTime: '16小时36分',
					loginAccounted: '43%',
					outTime: '6小时36分',
					outAccounted: '22%',
					restTime: '6小时36分',
					resAccounted: '22%'
				}, {
					date: '2016-05-02',
					name: '符号',
					session: '2',
					notReturn: '33%',
					amount: '0',
					invalids: '2',
					message: '3',
					loginTime: '26小时36分',
					onlineTime: '16小时36分',
					loginAccounted: '43%',
					outTime: '6小时36分',
					outAccounted: '22%',
					restTime: '6小时36分',
					resAccounted: '22%'
				}, {
					date: '2016-05-02',
					name: '符号',
					session: '2',
					notReturn: '33%',
					amount: '0',
					invalids: '2',
					message: '3',
					loginTime: '26小时36分',
					onlineTime: '16小时36分',
					loginAccounted: '43%',
					outTime: '6小时36分',
					outAccounted: '22%',
					restTime: '6小时36分',
					resAccounted: '22%'
				}, {
					date: '2016-05-02',
					name: '符号',
					session: '2',
					notReturn: '33%',
					amount: '0',
					invalids: '2',
					message: '3',
					loginTime: '26小时36分',
					onlineTime: '16小时36分',
					loginAccounted: '43%',
					outTime: '6小时36分',
					outAccounted: '22%',
					restTime: '6小时36分',
					resAccounted: '22%'
				}],
				Quality: [{
					date: '2016-05-02',
					name: '符号1',
					session: '3',
					notReturn: '33%',
					amount: '0',
					invalids: '2',
					message: '3',
					loginTime: '26小时36分',
					onlineTime: '16小时36分',
					loginAccounted: '43%',
					outTime: '6小时36分',
					outAccounted: '22%',
					restTime: '6小时36分',
					resAccounted: '22%'
				}, {
					date: '2016-05-02',
					name: '符号1',
					session: '2',
					notReturn: '33%',
					amount: '0',
					invalids: '2',
					message: '3',
					loginTime: '26小时36分',
					onlineTime: '16小时36分',
					loginAccounted: '43%',
					outTime: '6小时36分',
					outAccounted: '22%',
					restTime: '6小时36分',
					resAccounted: '22%'
				}, {
					date: '2016-05-02',
					name: '符号1',
					session: '2',
					notReturn: '33%',
					amount: '0',
					invalids: '2',
					message: '3',
					loginTime: '26小时36分',
					onlineTime: '16小时36分',
					loginAccounted: '43%',
					outTime: '6小时36分',
					outAccounted: '22%',
					restTime: '6小时36分',
					resAccounted: '22%'
				}, {
					date: '2016-05-02',
					name: '符号1',
					session: '2',
					notReturn: '33%',
					amount: '0',
					invalids: '2',
					message: '3',
					loginTime: '26小时36分',
					onlineTime: '16小时36分',
					loginAccounted: '43%',
					outTime: '6小时36分',
					outAccounted: '22%',
					restTime: '6小时36分',
					resAccounted: '22%'
				}, {
					date: '2016-05-02',
					name: '符号1',
					session: '2',
					notReturn: '33%',
					amount: '0',
					invalids: '2',
					message: '3',
					loginTime: '26小时36分',
					onlineTime: '16小时36分',
					loginAccounted: '43%',
					outTime: '6小时36分',
					outAccounted: '22%',
					restTime: '6小时36分',
					resAccounted: '22%'
				}, {
					date: '2016-05-02',
					name: '符号1',
					session: '2',
					notReturn: '33%',
					amount: '0',
					invalids: '2',
					message: '3',
					loginTime: '26小时36分',
					onlineTime: '16小时36分',
					loginAccounted: '43%',
					outTime: '6小时36分',
					outAccounted: '22%',
					restTime: '6小时36分',
					resAccounted: '22%'
				}],
				Performance: [{
					date: '2016-05-02',
					name: '符号2',
					session: '3',
					notReturn: '33%',
					amount: '0',
					invalids: '2',
					message: '3',
					loginTime: '26小时36分',
					onlineTime: '16小时36分',
					loginAccounted: '43%',
					outTime: '6小时36分',
					outAccounted: '22%',
					restTime: '6小时36分',
					resAccounted: '22%'
				}, {
					date: '2016-05-02',
					name: '符号2',
					session: '2',
					notReturn: '33%',
					amount: '0',
					invalids: '2',
					message: '3',
					loginTime: '26小时36分',
					onlineTime: '16小时36分',
					loginAccounted: '43%',
					outTime: '6小时36分',
					outAccounted: '22%',
					restTime: '6小时36分',
					resAccounted: '22%'
				}, {
					date: '2016-05-02',
					name: '符号2',
					session: '2',
					notReturn: '33%',
					amount: '0',
					invalids: '2',
					message: '3',
					loginTime: '26小时36分',
					onlineTime: '16小时36分',
					loginAccounted: '43%',
					outTime: '6小时36分',
					outAccounted: '22%',
					restTime: '6小时36分',
					resAccounted: '22%'
				}, {
					date: '2016-05-02',
					name: '符号2',
					session: '2',
					notReturn: '33%',
					amount: '0',
					invalids: '2',
					message: '3',
					loginTime: '26小时36分',
					onlineTime: '16小时36分',
					loginAccounted: '43%',
					outTime: '6小时36分',
					outAccounted: '22%',
					restTime: '6小时36分',
					resAccounted: '22%'
				}, {
					date: '2016-05-02',
					name: '符号2',
					session: '2',
					notReturn: '33%',
					amount: '0',
					invalids: '2',
					message: '3',
					loginTime: '26小时36分',
					onlineTime: '16小时36分',
					loginAccounted: '43%',
					outTime: '6小时36分',
					outAccounted: '22%',
					restTime: '6小时36分',
					resAccounted: '22%'
				}, {
					date: '2016-05-02',
					name: '符号2',
					session: '2',
					notReturn: '33%',
					amount: '0',
					invalids: '2',
					message: '3',
					loginTime: '26小时36分',
					onlineTime: '16小时36分',
					loginAccounted: '43%',
					outTime: '6小时36分',
					outAccounted: '22%',
					restTime: '6小时36分',
					resAccounted: '22%'
				}]
			}
		}
	}
</script>

<style>
</style>
